# Docker compose file for the Kafka setup
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: "bridge"
    ports:
      - "2181:2181"
  kafka:
    image: fastscore/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "172.17.0.1"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "notify:1:1,input:1:1,output:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "172.17.0.1:2181"
      KAFKA_LOG_RETENTION_BYTES: "5000000"
      CONTROLLER_MESSAGE_QUEUE_SIZE: 1
